# Generated by Django 2.1.5 on 2019-01-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='conduct_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='share_box',
            field=models.BooleanField(default=False),
        ),
    ]
