# Generated by Django 2.1.5 on 2019-01-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20190130_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='conduct_box',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='share_box',
            field=models.BooleanField(null=True),
        ),
    ]
