# Generated by Django 2.0.6 on 2019-01-31 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20190130_2328'),
        ('signup', '0002_auto_20190130_2322'),
    ]

    operations = [
    ]
