# Generated by Django 2.1.5 on 2019-02-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_auto_20190131_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='learn_or_gain',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
