# Generated by Django 2.1.5 on 2019-02-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_auto_20190131_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.CharField(default='', max_length=10),
        ),
    ]
