# Generated by Django 2.1.5 on 2019-02-01 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_merge_20190131_1053'),
        ('signup', '0006_auto_20190131_1931'),
    ]

    operations = [
    ]
