# Generated by Django 2.1.5 on 2019-02-11 23:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_auto_20190131_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='learn_or_gain',
            field=models.TextField(default='', max_length=1000, validators=[django.core.validators.MinValueValidator(250)]),
        ),
    ]
