# Generated by Django 2.1.5 on 2019-02-11 23:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0007_auto_20190211_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='learn_or_gain',
            field=models.TextField(default='', validators=[django.core.validators.MinValueValidator(250), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
