# Generated by Django 2.1.5 on 2019-02-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0009_auto_20190211_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='learn_or_gain',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
