# Generated by Django 2.1.5 on 2019-02-12 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0010_auto_20190211_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='preferred_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level_of_study',
            field=models.CharField(choices=[(None, ''), ('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Prefer not to disclose', 'Prefer not to disclose')], max_length=30),
        ),
    ]
