# Generated by Django 2.1.5 on 2019-02-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0011_auto_20190211_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender_other',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='race_other',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[(None, ''), ('Female', 'Female'), ('Male', 'Male'), ('Prefer not to disclose', 'Prefer not to disclose'), ('Other (Please Specify)', 'Other (Please Specify)')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='race',
            field=models.CharField(choices=[(None, ''), ('American Indian or Alaskan Native', 'American Indian or Alaskan Native'), ('Asian/Pacific Islander', 'Asian/Pacific Islander'), ('Black or African American', 'Black or African American'), ('Hispanic', 'Hispanic'), ('White/Caucasian', 'White/Caucasian'), ('Multiple ethnicity/Other (Please Specify)', 'Multiple ethnicity/Other (Please Specify)'), ('Prefer not to diclose', 'Prefer not to disclose')], default='', max_length=30),
        ),
    ]
