# Generated by Django 2.1.5 on 2019-02-28 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0011_auto_20190211_1623'),
        ('signup', '0007_merge_20190131_2322'),
    ]

    operations = [
    ]
