# Generated by Django 2.1.5 on 2019-03-03 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0012_merge_20190227_1651'),
        ('signup', '0013_myuser_created_at'),
    ]

    operations = [
    ]
