# Generated by Django 2.1.5 on 2019-03-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0016_auto_20190303_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='preferred_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
