# Generated by Django 2.1.5 on 2019-03-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0017_auto_20190303_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
